export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAIL = 'login_fail'
export const GET_POSTS_SUCCESS = 'get_posts_success'
export const GET_USERS_SUCCESS = 'get_users_success'
export const FILTER_PERSONAL_CONTACT_CHANGED = 'filter_personal_contact_changed'
export const GET_EVENTS_SUCCESS = 'get_events_success'